## DS4A | Team 37 | Data Cleaning

Load necessary libraries

In [1]:
import pandas as pd
import numpy as np
import sklearn
from sklearn.tree import DecisionTreeClassifier
from sklearn.ensemble import RandomForestClassifier
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import accuracy_score
from sklearn.model_selection import train_test_split

In [2]:
import warnings            
warnings.filterwarnings("ignore")

In [3]:
import pandas as pd
import os

In [4]:
# Set `main_dir` to the location of your `skill-soft` folder (for Mac).
main_dir = '/Volumes/GoogleDrive/My Drive/DS4A/Project'

# Make `data_dir` from the `main_dir` and
# remainder of the path to data directory.
data_dir = main_dir + "/Data_Cleaning"

# Set working directory.
os.chdir(data_dir)
# Check working directory.
print(os.getcwd())

df = pd.read_csv('Hospital_Inpatient_Discharges__SPARCS_De-Identified___2017.csv')

/Volumes/GoogleDrive/My Drive/DS4A/Project/Data_Cleaning

Open data file and study the general info

In [5]:
df.info()
df.describe()
df.isna().sum()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 2343569 entries, 0 to 2343568
Data columns (total 34 columns):
 #   Column                               Dtype
---  ------                               -----
 0   Hospital Service Area                object
 1   Hospital County                      object
 2   Operating Certificate Number         float64
 3   Permanent Facility Id                float64
 4   Facility Name                        object
 5   Age Group                            object
 6   Zip Code - 3 digits                  object
 7   Gender                               object
 8   Race                                 object
 9   Ethnicity                            object
 10  Length of Stay                       object
 11  Type of Admission                    object
 12  Patient Disposition                  object
 13  Discharge Year                       int64
 14  CCS Diagnosis Code                   int64
 15  CCS Diagnosis Description            object
 16  CCS Procedure Code                   int64
 17  CCS Procedure Description            object
 18  APR DRG Code                         int64
 19  APR DRG Description                  object
 20  APR MDC Code                         int64
 21  APR MDC Description                  object
 22  APR Severity of Illness Code         int64
 23  APR Severity of Illness Description  object
 24  APR Risk of Mortality                object
 25  APR Medical Surgical Description     object
 26  Payment Typology 1                   object
 27  Payment Typology 2                   object
 28  Payment Typology 3                   object
 29  Birth Weight                         object
 30  Abortion Edit Indicator              object
 31  Emergency Department Indicator       object
 32  Total Charges                        float64
 33  Total Costs                          float64
dtypes: float64(4), int64(6), object(24)
memory usage: 607.9+ MB

Hospital Service Area                     5155
Hospital County                           5155
Operating Certificate Number              5155
Permanent Facility Id                     5155
Facility Name                                0
Age Group                                    0
Zip Code - 3 digits                      39019
Gender                                       0
Race                                         0
Ethnicity                                    0
Length of Stay                               0
Type of Admission                            0
Patient Disposition                          0
Discharge Year                               0
CCS Diagnosis Code                           0
CCS Diagnosis Description                    0
CCS Procedure Code                           0
CCS Procedure Description                    0
APR DRG Code                                 0
APR DRG Description                          0
APR MDC Code                                 0
APR MDC Description                          0
APR Severity of Illness Code                 0
APR Severity of Illness Description        240
APR Risk of Mortality                      240
APR Medical Surgical Description             0
Payment Typology 1                           0
Payment Typology 2                      878722
Payment Typology 3                     1737244
Birth Weight                           2115685
Abortion Edit Indicator                      0
Emergency Department Indicator               0
Total Charges                                0
Total Costs                                  0
dtype: int64

# 1. Deal with missing values

### Investigate columns that have missing values

Investigate why Birth Weight has such a great number of missing values

In [6]:
#Investigate why Birth Weight has such a great number of missing values
with pd.option_context('display.max_rows', None, 'display.max_columns', 34): 
    print(df[df['Birth Weight'].isnull()].head(10))

  Hospital Service Area Hospital County  Operating Certificate Number  \
0         Hudson Valley     Westchester                     5903001.0
1         Hudson Valley     Westchester                     5903001.0
2         Hudson Valley     Westchester                     5903001.0
3         Hudson Valley     Westchester                     5903001.0
4         Hudson Valley     Westchester                     5903001.0
5         Hudson Valley     Westchester                     5903001.0
6         Hudson Valley     Westchester                     5903001.0
7         Hudson Valley     Westchester                     5903001.0
8         Hudson Valley     Westchester                     5903001.0
9         Hudson Valley     Westchester                     5903001.0

   Permanent Facility Id                     Facility Name Age Group  \
0                 1061.0  Montefiore Mount Vernon Hospital  30 to 49
1                 1061.0  Montefiore Mount Vernon Hospital  50 to 69
2                 1061.0  Montefiore Mount Vernon Hospital  30 to 49
3                 1061.0  Montefiore Mount Vernon Hospital  50 to 69
4                 1061.0  Montefiore Mount Vernon Hospital  18 to 29
5                 1061.0  Montefiore Mount Vernon Hospital  50 to 69
6                 1061.0  Montefiore Mount Vernon Hospital  30 to 49
7                 1061.0  Montefiore Mount Vernon Hospital  30 to 49
8                 1061.0  Montefiore Mount Vernon Hospital  50 to 69
9                 1061.0  Montefiore Mount Vernon Hospital  50 to 69

  Zip Code - 3 digits Gender                    Race          Ethnicity  \
0                 NaN      M                   White  Not Span/Hispanic
1                 105      M                   White   Spanish/Hispanic
2                 105      F                   White            Unknown
3                 105      F                   White  Not Span/Hispanic
4                 105      F                   White   Spanish/Hispanic
5                 105      M  Black/African American  Not Span/Hispanic
6                 105      F  Black/African American  Not Span/Hispanic
7                 105      F  Black/African American            Unknown
8                 105      M  Black/African American  Not Span/Hispanic
9                 107      F  Black/African American  Not Span/Hispanic

  Length of Stay Type of Admission    Patient Disposition  Discharge Year  \
0             21          Elective      Home or Self Care            2017
1              8         Emergency   Skilled Nursing Home            2017
2              6         Emergency  Court/Law Enforcement            2017
3              4         Emergency   Skilled Nursing Home            2017
4              4         Emergency  Court/Law Enforcement            2017
5              3         Emergency    Short-term Hospital            2017
6              3         Emergency  Court/Law Enforcement            2017
7              4         Emergency      Home or Self Care            2017
8              4         Emergency      Home or Self Care            2017
9              3         Emergency      Home or Self Care            2017

   CCS Diagnosis Code                          CCS Diagnosis Description  \
0                 659        Schizophrenia and other psychotic disorders
1                  99  Hypertension with complications and secondary ...
2                 161               Other diseases of kidney and ureters
3                 238  Complications of surgical procedures or medica...
4                   2                       Septicemia (except in labor)
5                 660                          Alcohol-related disorders
6                 102                             Nonspecific chest pain
7                  50               Diabetes mellitus with complications
8                 245                                            Syncope
9                 245                                            Syncope

   CCS Procedure Code CCS Procedure Description  APR DRG Code  \
0                   0                   NO PROC           750
1                 108       INDWELLING CATHETER           194
2                 102    URETERAL CATHETERIZATN           465
3                 222         BLOOD TRANSFUSION           721
4                   0                   NO PROC           720
5                 222         BLOOD TRANSFUSION           280
6                   0                   NO PROC           203
7                 222         BLOOD TRANSFUSION           420
8                 231    OTHER THERAPEUTIC PRCS           204
9                   0                   NO PROC           204

                                 APR DRG Description  APR MDC Code  \
0                                      Schizophrenia            19
1                                      Heart failure             5
2  Urinary stones & acquired upper urinary tract ...            11
3  Post-operative, post-traumatic, other device i...            18
4               Septicemia & disseminated infections            18
5                            Alcoholic liver disease             7
6                                         Chest pain             5
7                                           Diabetes            10
8                                 Syncope & collapse             5
9                                 Syncope & collapse             5

                                 APR MDC Description  \
0                      Mental Diseases and Disorders
1   Diseases and Disorders of the Circulatory System
2  Diseases and Disorders of the Kidney and Urina...
3  Infectious and Parasitic Diseases, Systemic or...
4  Infectious and Parasitic Diseases, Systemic or...
5  Diseases and Disorders of the Hepatobiliary Sy...
6   Diseases and Disorders of the Circulatory System
7  Endocrine, Nutritional and Metabolic Diseases ...
8   Diseases and Disorders of the Circulatory System
9   Diseases and Disorders of the Circulatory System

   APR Severity of Illness Code APR Severity of Illness Description  \
0                             2                            Moderate
1                             3                               Major
2                             2                            Moderate
3                             2                            Moderate
4                             2                            Moderate
5                             3                               Major
6                             2                            Moderate
7                             3                               Major
8                             1                               Minor
9                             1                               Minor

  APR Risk of Mortality APR Medical Surgical Description  \
0                 Minor                          Medical
1              Moderate                          Medical
2              Moderate                          Medical
3              Moderate                          Medical
4                 Minor                          Medical
5                 Major                          Medical
6                 Minor                          Medical
7                 Major                          Medical
8                 Minor                          Medical
9                 Minor                          Medical

          Payment Typology 1        Payment Typology 2 Payment Typology 3  \
0                   Medicare                  Medicare           Self-Pay
1                   Medicaid                  Medicaid           Self-Pay
2  Department of Corrections                  Self-Pay                NaN
3                   Medicaid                  Medicaid           Self-Pay
4  Department of Corrections                  Self-Pay                NaN
5                   Medicare                  Medicare           Self-Pay
6                   Medicaid                  Self-Pay                NaN
7                   Medicaid                  Medicaid           Medicaid
8                   Medicaid                  Medicaid           Self-Pay
9   Private Health Insurance  Private Health Insurance           Self-Pay

  Birth Weight Abortion Edit Indicator Emergency Department Indicator  \
0          NaN                       N                              N
1          NaN                       N                              N
2          NaN                       N                              N
3          NaN                       N                              N
4          NaN                       N                              N
5          NaN                       N                              N
6          NaN                       N                              N
7          NaN                       N                              N
8          NaN                       N                              N
9          NaN                       N                              N

   Total Charges  Total Costs
0      114168.00     40464.04
1       58517.00     26046.50
2       39647.04     17397.59
3       36031.09     16118.84
4       30534.00     11921.05
5       49290.08     18503.26
6       20511.00      9103.80
7       55172.00     17682.94
8       31034.00     12649.61
9       25027.00      9751.06

In [7]:
a = df['CCS Diagnosis Code'].unique()
print(sorted(a))

[1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50, 51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 76, 77, 78, 79, 80, 81, 82, 83, 84, 85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98, 99, 100, 101, 102, 103, 104, 105, 106, 107, 108, 109, 110, 111, 112, 113, 114, 115, 116, 117, 118, 119, 120, 121, 122, 123, 124, 125, 126, 127, 128, 129, 130, 131, 132, 133, 134, 135, 136, 137, 138, 139, 140, 141, 142, 143, 144, 145, 146, 147, 148, 149, 151, 152, 153, 154, 155, 156, 157, 158, 159, 160, 161, 162, 163, 164, 165, 166, 167, 168, 169, 170, 171, 172, 173, 174, 175, 176, 177, 178, 179, 180, 181, 182, 183, 184, 185, 186, 187, 188, 189, 190, 191, 192, 193, 194, 195, 196, 197, 198, 199, 200, 201, 202, 203, 204, 205, 206, 207, 208, 209, 210, 211, 212, 213, 214, 215, 216, 217, 218, 219, 220, 221, 222, 223, 224, 225, 226, 227, 228, 229, 230, 231, 232, 233, 234, 235, 236, 237, 238, 239, 240, 241, 242, 243, 244, 245, 246, 247, 248, 249, 250, 251, 252, 253, 254, 255, 256, 257, 258, 259, 650, 651, 652, 653, 654, 655, 656, 657, 658, 659, 660, 661, 662, 663, 670, 2617]

In [8]:
df.loc[(df['Birth Weight'].isnull()) & (df['CCS Diagnosis Code'] == 11)]['CCS Diagnosis Code'].count()

2322

Investigate missng values in zip code

In [10]:
with pd.option_context('display.max_rows', None, 'display.max_columns', 34): 
    print(df[df['Zip Code - 3 digits'].isnull()].head(10))

    Hospital Service Area Hospital County  Operating Certificate Number  \
0           Hudson Valley     Westchester                     5903001.0
25          Hudson Valley     Westchester                     5904001.0
28                    NaN             NaN                           NaN
61          Hudson Valley        Sullivan                     5263000.0
213         New York City       Manhattan                     7002002.0
225         New York City       Manhattan                     7002002.0
277         New York City       Manhattan                     7002024.0
405         New York City       Manhattan                     7002032.0
426         New York City       Manhattan                     7002032.0
471         New York City       Manhattan                     7002032.0

     Permanent Facility Id                     Facility Name    Age Group  \
0                   1061.0  Montefiore Mount Vernon Hospital     30 to 49
25                  1072.0  Montefiore New Rochelle Hospital     18 to 29
28                     NaN      Redacted for Confidentiality      0 to 17
61                   971.0  Catskill Regional Medical Center     30 to 49
213                 1439.0           Mount Sinai Beth Israel  70 or Older
225                 1439.0           Mount Sinai Beth Israel      0 to 17
277                 1456.0              Mount Sinai Hospital     18 to 29
405                 1466.0                  Mount Sinai West     30 to 49
426                 1466.0                  Mount Sinai West     50 to 69
471                 1466.0                  Mount Sinai West     30 to 49

    Zip Code - 3 digits Gender                    Race          Ethnicity  \
0                   NaN      M                   White  Not Span/Hispanic
25                  NaN      M                   White  Not Span/Hispanic
28                  NaN      F                   White  Not Span/Hispanic
61                  NaN      M  Black/African American  Not Span/Hispanic
213                 NaN      M                   White  Not Span/Hispanic
225                 NaN      M              Other Race            Unknown
277                 NaN      F              Other Race  Not Span/Hispanic
405                 NaN      M                   White            Unknown
426                 NaN      F                   White   Spanish/Hispanic
471                 NaN      F                   White  Not Span/Hispanic

    Length of Stay Type of Admission           Patient Disposition  \
0               21          Elective             Home or Self Care
25               2         Emergency             Home or Self Care
28               2         Emergency             Home or Self Care
61               6         Emergency       Another Type Not Listed
213              1            Urgent  Home w/ Home Health Services
225              2           Newborn             Home or Self Care
277              2          Elective             Home or Self Care
405             78         Emergency                Hospice - Home
426              2          Elective  Home w/ Home Health Services
471              1          Elective             Home or Self Care

     Discharge Year  CCS Diagnosis Code  \
0              2017                 659
25             2017                  83
28             2017                 229
61             2017                 659
213            2017                 143
225            2017                 218
277            2017                 192
405            2017                   5
426            2017                 203
471            2017                 134

                       CCS Diagnosis Description  CCS Procedure Code  \
0    Schizophrenia and other psychotic disorders                   0
25                         Epilepsy; convulsions                 177
28                        Fracture of upper limb                 148
61   Schizophrenia and other psychotic disorders                   0
213                             Abdominal hernia                  86
225                                     Liveborn                 220
277                  Umbilical cord complication                 137
405                                HIV infection                   9
426                               Osteoarthritis                 152
471              Other upper respiratory disease                  42

    CCS Procedure Description  APR DRG Code  \
0                     NO PROC           750
25     COMP AXIAL TOMOGR (CT)            53
28     OT FRACTURE/DISLOC PRC           315
61                    NO PROC           750
213       OTHER HERNIA REPAIR           227
225    OPHTHALM-/OT-OLOGIC DX           640
277   OT PRCS TO ASSIST DELIV           560
405    OTHER OR THER NERV SYS           890
426         ARTHROPLASTY KNEE           302
471    OT OR RX PRCS RESP SYS           121

                                   APR DRG Description  APR MDC Code  \
0                                        Schizophrenia            19
25                                             Seizure             1
28   Shoulder, upper arm & forearm procedures excep...             8
61                                       Schizophrenia            19
213  Hernia procedures except inguinal, femoral & u...             6
225  Neonate birthwt >2499g, normal newborn or neon...            15
277                                   Vaginal delivery            14
405        HIV w multiple major HIV related conditions            24
426                             Knee joint replacement             8
471               Other respiratory & chest procedures             4

                                   APR MDC Description  \
0                        Mental Diseases and Disorders
25        Diseases and Disorders of the Nervous System
28   Diseases and Disorders of the Musculoskeletal ...
61                       Mental Diseases and Disorders
213     Diseases and Disorders of the Digestive System
225  Newborns and Other Neonates with Conditions Or...
277           Pregnancy, Childbirth and the Puerperium
405            Human Immunodeficiency Virus Infections
426  Diseases and Disorders of the Musculoskeletal ...
471   Diseases and Disorders of the Respiratory System

     APR Severity of Illness Code APR Severity of Illness Description  \
0                               2                            Moderate
25                              2                            Moderate
28                              2                            Moderate
61                              2                            Moderate
213                             2                            Moderate
225                             1                               Minor
277                             1                               Minor
405                             4                             Extreme
426                             1                               Minor
471                             3                               Major

    APR Risk of Mortality APR Medical Surgical Description  \
0                   Minor                          Medical
25               Moderate                          Medical
28                  Minor                         Surgical
61                  Minor                          Medical
213              Moderate                         Surgical
225                 Minor                          Medical
277                 Minor                          Medical
405               Extreme                          Medical
426                 Minor                         Surgical
471              Moderate                         Surgical

           Payment Typology 1      Payment Typology 2 Payment Typology 3  \
0                    Medicare                Medicare           Self-Pay
25     Blue Cross/Blue Shield                Self-Pay                NaN
28     Blue Cross/Blue Shield                Self-Pay                NaN
61   Private Health Insurance                     NaN                NaN
213                  Medicare  Blue Cross/Blue Shield           Self-Pay
225  Private Health Insurance                Self-Pay                NaN
277  Private Health Insurance                Self-Pay                NaN
405    Blue Cross/Blue Shield                Medicaid           Self-Pay
426    Blue Cross/Blue Shield                Self-Pay                NaN
471                  Medicare                Medicaid           Self-Pay

    Birth Weight Abortion Edit Indicator Emergency Department Indicator  \
0            NaN                       N                              N
25           NaN                       N                              N
28           NaN                       N                              N
61           NaN                       N                              Y
213          NaN                       N                              N
225         3300                       N                              N
277          NaN                       N                              N
405          NaN                       N                              Y
426          NaN                       N                              N
471          NaN                       N                              N

     Total Charges  Total Costs
0        114168.00     40464.04
25        22554.00      8548.93
28        39565.96     15953.31
61        12169.45      5528.52
213       18965.80      6403.86
225        9165.00       943.90
277       19986.55      7637.10
405     1294606.32    378528.65
426       66457.53     24624.93
471       24849.52     12638.12

In [11]:
df[df['Facility Name']== 'Montefiore Mount Vernon Hospital'].head(5)

,Hospital Service Area,Hospital County,Operating Certificate Number,Permanent Facility Id,Facility Name,Age Group,Zip Code - 3 digits,Gender,Race,Ethnicity,...,APR Risk of Mortality,APR Medical Surgical Description,Payment Typology 1,Payment Typology 2,Payment Typology 3,Birth Weight,Abortion Edit Indicator,Emergency Department Indicator,Total Charges,Total Costs
0,Hudson Valley,Westchester,5903001.0,1061.0,Montefiore Mount Vernon Hospital,30 to 49,NaN,M,White,Not Span/Hispanic,...,Minor,Medical,Medicare,Medicare,Self-Pay,NaN,N,N,114168.00,40464.04
1,Hudson Valley,Westchester,5903001.0,1061.0,Montefiore Mount Vernon Hospital,50 to 69,105,M,White,Spanish/Hispanic,...,Moderate,Medical,Medicaid,Medicaid,Self-Pay,NaN,N,N,58517.00,26046.50
2,Hudson Valley,Westchester,5903001.0,1061.0,Montefiore Mount Vernon Hospital,30 to 49,105,F,White,Unknown,...,Moderate,Medical,Department of Corrections,Self-Pay,NaN,NaN,N,N,39647.04,17397.59
3,Hudson Valley,Westchester,5903001.0,1061.0,Montefiore Mount Vernon Hospital,50 to 69,105,F,White,Not Span/Hispanic,...,Moderate,Medical,Medicaid,Medicaid,Self-Pay,NaN,N,N,36031.09,16118.84
4,Hudson Valley,Westchester,5903001.0,1061.0,Montefiore Mount Vernon Hospital,18 to 29,105,F,White,Spanish/Hispanic,...,Minor,Medical,Department of Corrections,Self-Pay,NaN,NaN,N,N,30534.00,11921.05

### Recover missing zip codes from the same hospital 

- Create a dictionary that has info on hospital id and zip code (extract rows from the current data, remove duplicate rows)
- Merge with the current dataset

In [12]:
zip_code = df[['Permanent Facility Id', 'Operating Certificate Number','Facility Name', 'Zip Code - 3 digits']]

In [13]:
print('Number of unique "Permanent Facility Id":',len(df['Permanent Facility Id'].unique()))
print('Number of unique "Operating Certificate Number":',len(df['Operating Certificate Number'].unique()))
print('Number of unique "Facility Name":',len(df['Facility Name'].unique()))

Number of unique "Permanent Facility Id": 212
Number of unique "Operating Certificate Number": 175
Number of unique "Facility Name": 211

In [14]:
#Remove rows with missing value
zip_code_clean = zip_code.dropna(subset=['Zip Code - 3 digits'])
zip_code_clean.isna().sum()

Permanent Facility Id           0
Operating Certificate Number    0
Facility Name                   0
Zip Code - 3 digits             0
dtype: int64

In [15]:
zip_code_clean_1 = zip_code_clean.drop_duplicates(subset=['Permanent Facility Id'])

zip_code_clean_1[zip_code_clean_1.duplicated()].head() #Done

zip_code_clean_1.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 210 entries, 1 to 1125696
Data columns (total 4 columns):
 #   Column                        Non-Null Count  Dtype
---  ------                        --------------  -----
 0   Permanent Facility Id         210 non-null    float64
 1   Operating Certificate Number  210 non-null    float64
 2   Facility Name                 210 non-null    object
 3   Zip Code - 3 digits           210 non-null    object
dtypes: float64(2), object(2)
memory usage: 8.2+ KB

In [16]:
df_full_zipcode = pd.merge(df, zip_code_clean_1, how='left', on='Permanent Facility Id')

df_full_zipcode.isna().sum()

Hospital Service Area                     5155
Hospital County                           5155
Operating Certificate Number_x            5155
Permanent Facility Id                     5155
Facility Name_x                              0
Age Group                                    0
Zip Code - 3 digits_x                    39019
Gender                                       0
Race                                         0
Ethnicity                                    0
Length of Stay                               0
Type of Admission                            0
Patient Disposition                          0
Discharge Year                               0
CCS Diagnosis Code                           0
CCS Diagnosis Description                    0
CCS Procedure Code                           0
CCS Procedure Description                    0
APR DRG Code                                 0
APR DRG Description                          0
APR MDC Code                                 0
APR MDC Description                          0
APR Severity of Illness Code                 0
APR Severity of Illness Description        240
APR Risk of Mortality                      240
APR Medical Surgical Description             0
Payment Typology 1                           0
Payment Typology 2                      878722
Payment Typology 3                     1737244
Birth Weight                           2115685
Abortion Edit Indicator                      0
Emergency Department Indicator               0
Total Charges                                0
Total Costs                                  0
Operating Certificate Number_y            5161
Facility Name_y                           5161
Zip Code - 3 digits_y                     5161
dtype: int64

There are still missing zip codes, let investigate why

In [17]:
df_full_zipcode[df_full_zipcode['Zip Code - 3 digits_y'].isnull()]['Facility Name_x'].unique()

array(['Redacted for Confidentiality',
       'Albany Medical Center - South Clinical Campus'], dtype=object)

Because we dont have zip code for 
- Albany Medical Center - South Clinical Campus: this can be googled 
- Redacted for Confidentiality: we can't do anything about this

In [18]:
#Have a look at the Albany Medical Center - South Clinical Campus
df[df['Facility Name'] == 'Albany Medical Center - South Clinical Campus']

,Hospital Service Area,Hospital County,Operating Certificate Number,Permanent Facility Id,Facility Name,Age Group,Zip Code - 3 digits,Gender,Race,Ethnicity,...,APR Risk of Mortality,APR Medical Surgical Description,Payment Typology 1,Payment Typology 2,Payment Typology 3,Birth Weight,Abortion Edit Indicator,Emergency Department Indicator,Total Charges,Total Costs
485306,Capital/Adirond,Albany,101000.0,2.0,Albany Medical Center - South Clinical Campus,50 to 69,NaN,F,White,Not Span/Hispanic,...,Minor,Surgical,Blue Cross/Blue Shield,NaN,NaN,NaN,N,N,15200.29,5929.01
485307,Capital/Adirond,Albany,101000.0,2.0,Albany Medical Center - South Clinical Campus,50 to 69,NaN,F,White,Not Span/Hispanic,...,Moderate,Surgical,Medicare,NaN,NaN,NaN,N,N,22527.77,6347.42
800703,Capital/Adirond,Albany,101000.0,2.0,Albany Medical Center - South Clinical Campus,50 to 69,NaN,F,White,Not Span/Hispanic,...,Minor,Surgical,Blue Cross/Blue Shield,NaN,NaN,NaN,N,N,36810.92,13565.10
1134235,Capital/Adirond,Albany,101000.0,2.0,Albany Medical Center - South Clinical Campus,50 to 69,NaN,F,White,Not Span/Hispanic,...,Moderate,Surgical,Blue Cross/Blue Shield,NaN,NaN,NaN,N,N,12613.10,4986.62
1134236,Capital/Adirond,Albany,101000.0,2.0,Albany Medical Center - South Clinical Campus,18 to 29,NaN,F,White,Not Span/Hispanic,...,Minor,Medical,Medicare,NaN,NaN,NaN,N,N,8976.79,3738.74
1637241,Capital/Adirond,Albany,101000.0,2.0,Albany Medical Center - South Clinical Campus,18 to 29,NaN,F,White,Not Span/Hispanic,...,Minor,Surgical,Blue Cross/Blue Shield,Medicare,NaN,NaN,N,N,11143.94,5074.75

In [19]:
zip_code_clean_1.head()

,Permanent Facility Id,Operating Certificate Number,Facility Name,Zip Code - 3 digits
1,1061.0,5903001.0,Montefiore Mount Vernon Hospital,105
11,1072.0,5904001.0,Montefiore New Rochelle Hospital,108
30,1439.0,7002002.0,Mount Sinai Beth Israel,100
32,971.0,5263000.0,Catskill Regional Medical Center,127
136,1324.0,7002002.0,Mount Sinai Brooklyn,112

Add zip code of Albany Medical Center - South Clinical Campus

In [20]:
albany = pd.DataFrame([[2.0, 101000.0, 'Albany Medical Center - South Clinical Campus', 122]], 
                      columns=['Permanent Facility Id', 'Operating Certificate Number', 'Facility Name', 'Zip Code - 3 digits'])

zip_code_clean_2 = zip_code_clean_1.append(albany)

zip_code_clean_2.tail()

,Permanent Facility Id,Operating Certificate Number,Facility Name,Zip Code - 3 digits
702780,114.0,427000.0,TLC Health Network Lake Shore Hospital,141
707558,804.0,4402000.0,Massena Memorial Hospital,136
1010230,1005.0,5601000.0,Glens Falls Hospital,128
1125696,414.0,2701006.0,Monroe Community Hospital,146
0,2.0,101000.0,Albany Medical Center - South Clinical Campus,122

Merge with the current data to get all of the zip code we can recover, except for the redacted ones

In [21]:
df_full_zipcode_1 = pd.merge(df, zip_code_clean_2, how='left', on='Permanent Facility Id')\
    .drop(['Operating Certificate Number_y','Facility Name_y', 'Zip Code - 3 digits_x'], axis=1)\
    .rename(columns={"Zip Code - 3 digits_y": "Zip Code - 3 digits", 
                     "Operating Certificate Number_x":"Operating Certificate Number",
                    "Facility Name_x": "Facility Name"})

In [22]:
df_full_zipcode_1.isna().sum()

Hospital Service Area                     5155
Hospital County                           5155
Operating Certificate Number              5155
Permanent Facility Id                     5155
Facility Name                                0
Age Group                                    0
Gender                                       0
Race                                         0
Ethnicity                                    0
Length of Stay                               0
Type of Admission                            0
Patient Disposition                          0
Discharge Year                               0
CCS Diagnosis Code                           0
CCS Diagnosis Description                    0
CCS Procedure Code                           0
CCS Procedure Description                    0
APR DRG Code                                 0
APR DRG Description                          0
APR MDC Code                                 0
APR MDC Description                          0
APR Severity of Illness Code                 0
APR Severity of Illness Description        240
APR Risk of Mortality                      240
APR Medical Surgical Description             0
Payment Typology 1                           0
Payment Typology 2                      878722
Payment Typology 3                     1737244
Birth Weight                           2115685
Abortion Edit Indicator                      0
Emergency Department Indicator               0
Total Charges                                0
Total Costs                                  0
Zip Code - 3 digits                       5155
dtype: int64

In [23]:
df_full_zipcode_1[df_full_zipcode_1['Hospital Service Area'].isnull()].head()

,Hospital Service Area,Hospital County,Operating Certificate Number,Permanent Facility Id,Facility Name,Age Group,Gender,Race,Ethnicity,Length of Stay,...,APR Medical Surgical Description,Payment Typology 1,Payment Typology 2,Payment Typology 3,Birth Weight,Abortion Edit Indicator,Emergency Department Indicator,Total Charges,Total Costs,Zip Code - 3 digits
28,NaN,NaN,NaN,NaN,Redacted for Confidentiality,0 to 17,F,White,Not Span/Hispanic,2,...,Surgical,Blue Cross/Blue Shield,Self-Pay,NaN,NaN,N,N,39565.96,15953.31,NaN
595,NaN,NaN,NaN,NaN,Redacted for Confidentiality,18 to 29,F,White,Not Span/Hispanic,1,...,Medical,Blue Cross/Blue Shield,Medicaid,NaN,NaN,Y,N,7089.08,3101.13,NaN
839,NaN,NaN,NaN,NaN,Redacted for Confidentiality,18 to 29,F,Black/African American,Not Span/Hispanic,1,...,Surgical,Medicaid,Medicaid,Self-Pay,NaN,Y,N,17850.46,7671.21,NaN
2227,NaN,NaN,NaN,NaN,Redacted for Confidentiality,0 to 17,F,Other Race,Spanish/Hispanic,1,...,Medical,Medicaid,NaN,NaN,NaN,Y,Y,21040.48,4112.07,NaN
2723,NaN,NaN,NaN,NaN,Redacted for Confidentiality,30 to 49,F,Black/African American,Not Span/Hispanic,1,...,Surgical,Medicaid,NaN,NaN,NaN,Y,Y,30815.99,6028.16,NaN

### Remove rows that have NAs in the two columns that has a small number of NAs (< 0.01%)

In [24]:
df_clean = df_full_zipcode_1.dropna(subset=['APR Severity of Illness Description', 'APR Risk of Mortality'])
df_clean.isna().sum()
df_clean.dtypes

Hospital Service Area                   object
Hospital County                         object
Operating Certificate Number           float64
Permanent Facility Id                  float64
Facility Name                           object
Age Group                               object
Gender                                  object
Race                                    object
Ethnicity                               object
Length of Stay                          object
Type of Admission                       object
Patient Disposition                     object
Discharge Year                           int64
CCS Diagnosis Code                       int64
CCS Diagnosis Description               object
CCS Procedure Code                       int64
CCS Procedure Description               object
APR DRG Code                             int64
APR DRG Description                     object
APR MDC Code                             int64
APR MDC Description                     object
APR Severity of Illness Code             int64
APR Severity of Illness Description     object
APR Risk of Mortality                   object
APR Medical Surgical Description        object
Payment Typology 1                      object
Payment Typology 2                      object
Payment Typology 3                      object
Birth Weight                            object
Abortion Edit Indicator                 object
Emergency Department Indicator          object
Total Charges                          float64
Total Costs                            float64
Zip Code - 3 digits                     object
dtype: object

# 2. Deal with incorrect data type

'Length of Stay' should be numeric, but it's currently an object, let's have a look at the variable

In [25]:
df_clean['Length of Stay'].unique()

array(['21', '8', '6', '4', '3', '1', '27', '14', '5', '2', '26', '24',
       '25', '20', '12', '11', '7', '9', '13', '10', '62', '60', '42',
       '36', '29', '28', '15', '16', '17', '44', '22', '64', '37', '19',
       '78', '65', '39', '35', '118', '68', '49', '30', '34', '18', '50',
       '56', '61', '41', '45', '51', '47', '31', '23', '80', '52', '38',
       '32', '113', '120 +', '71', '66', '48', '96', '54', '43', '91',
       '67', '46', '90', '33', '57', '74', '88', '81', '83', '75', '55',
       '107', '77', '72', '70', '59', '103', '110', '76', '40', '101',
       '73', '69', '53', '58', '98', '63', '106', '84', '85', '79', '108',
       '97', '92', '102', '99', '109', '94', '117', '105', '114', '104',
       '82', '112', '100', '116', '86', '119', '95', '87', '89', '93',
       '111', '115'], dtype=object)

Because there is "120+" value --> object. Let treat "120+" as 120 and convert it to numeric

In [26]:
df_clean['Length of Stay'] = df_clean['Length of Stay'].apply(lambda x: str(x).split(' ')[0])
df_clean['Length of Stay'] = pd.to_numeric(df_clean['Length of Stay'])
df_clean['Length of Stay'].unique()

array([ 21,   8,   6,   4,   3,   1,  27,  14,   5,   2,  26,  24,  25,
        20,  12,  11,   7,   9,  13,  10,  62,  60,  42,  36,  29,  28,
        15,  16,  17,  44,  22,  64,  37,  19,  78,  65,  39,  35, 118,
        68,  49,  30,  34,  18,  50,  56,  61,  41,  45,  51,  47,  31,
        23,  80,  52,  38,  32, 113, 120,  71,  66,  48,  96,  54,  43,
        91,  67,  46,  90,  33,  57,  74,  88,  81,  83,  75,  55, 107,
        77,  72,  70,  59, 103, 110,  76,  40, 101,  73,  69,  53,  58,
        98,  63, 106,  84,  85,  79, 108,  97,  92, 102,  99, 109,  94,
       117, 105, 114, 104,  82, 112, 100, 116,  86, 119,  95,  87,  89,
        93, 111, 115])

Birth Weight should be numeric, but it's an object. Let's look at the variable

In [29]:
df_clean['Birth Weight'].unique()

array([nan, 3300.0, 3100.0, 3000.0, 3400.0, 2500.0, 3800.0, 2300.0,
       2900.0, 3600.0, 1300.0, 2400.0, 2100.0, 2200.0, 1800.0, 3700.0,
       3200.0, 4000.0, 3500.0, 800.0, 2600.0, 2800.0, 1500.0, 700.0,
       5800.0, 1600.0, 2000.0, 3900.0, 4400.0, 4100.0, 4300.0, 4800.0,
       2700.0, 1900.0, 4200.0, 4500.0, 900.0, 4700.0, 500.0, 1700.0,
       1100.0, 4600.0, 400.0, 600.0, 1400.0, 5100.0, 300.0, 1000.0,
       1200.0, 5200.0, 4900.0, 5000.0, 5500.0, 5400.0, 200.0, 8800.0,
       100.0, 5300.0, 6000.0, 7000.0, 7800.0, 9000.0, 6800.0, 8000.0,
       6600.0, 5600.0, 7400.0, 8900.0, 8200.0, 6400.0, 6200.0, 8100.0,
       '04000', '03200', '03100', '03700', '03300', '03900', '02400',
       '03000', '02900', '03400', '02700', '03500', '02600', '03800',
       '03600', '00500', '02500', '04100', '04300', '02800', '00700',
       '02300', '01900', '02000', '02200', '04800', '04200', '01500',
       '00300', 'UNKN', '01600', '04400', '01400', '02100', '00800',
       '01300', '04700', '04500', '01800', '04900', '00900', '01200',
       '00600', '01700', '01000', '01100', '04600', '05000', '05300',
       '00100', '00400', '06000', '05400', 6100.0, '06100', 5700.0,
       '05100', '06300', '05500', 6900.0, '05200', '05800', '08300',
       '11700', '08000'], dtype=object)

Because it contains "UNKN" and also weird presentation of number, like 04000. We can:
- Convert UNKN (Unknown) to NULL
- Convert all other to numeric

In [30]:
df_clean_1 = df_clean
df_clean_1['Birth Weight_clean'] = df_clean_1['Birth Weight'].apply(pd.to_numeric, errors='coerce')
df_clean_1['Birth Weight_clean'].unique()

array([   nan,  3300.,  3100.,  3000.,  3400.,  2500.,  3800.,  2300.,
        2900.,  3600.,  1300.,  2400.,  2100.,  2200.,  1800.,  3700.,
        3200.,  4000.,  3500.,   800.,  2600.,  2800.,  1500.,   700.,
        5800.,  1600.,  2000.,  3900.,  4400.,  4100.,  4300.,  4800.,
        2700.,  1900.,  4200.,  4500.,   900.,  4700.,   500.,  1700.,
        1100.,  4600.,   400.,   600.,  1400.,  5100.,   300.,  1000.,
        1200.,  5200.,  4900.,  5000.,  5500.,  5400.,   200.,  8800.,
         100.,  5300.,  6000.,  7000.,  7800.,  9000.,  6800.,  8000.,
        6600.,  5600.,  7400.,  8900.,  8200.,  6400.,  6200.,  8100.,
        6100.,  5700.,  6300.,  6900.,  8300., 11700.])

In [31]:
df_clean_1[df_clean_1['Birth Weight'] == 'UNKN']
df_clean_1.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 2343329 entries, 0 to 2343568
Data columns (total 35 columns):
 #   Column                               Dtype
---  ------                               -----
 0   Hospital Service Area                object
 1   Hospital County                      object
 2   Operating Certificate Number         float64
 3   Permanent Facility Id                float64
 4   Facility Name                        object
 5   Age Group                            object
 6   Gender                               object
 7   Race                                 object
 8   Ethnicity                            object
 9   Length of Stay                       int64
 10  Type of Admission                    object
 11  Patient Disposition                  object
 12  Discharge Year                       int64
 13  CCS Diagnosis Code                   int64
 14  CCS Diagnosis Description            object
 15  CCS Procedure Code                   int64
 16  CCS Procedure Description            object
 17  APR DRG Code                         int64
 18  APR DRG Description                  object
 19  APR MDC Code                         int64
 20  APR MDC Description                  object
 21  APR Severity of Illness Code         int64
 22  APR Severity of Illness Description  object
 23  APR Risk of Mortality                object
 24  APR Medical Surgical Description     object
 25  Payment Typology 1                   object
 26  Payment Typology 2                   object
 27  Payment Typology 3                   object
 28  Birth Weight                         object
 29  Abortion Edit Indicator              object
 30  Emergency Department Indicator       object
 31  Total Charges                        float64
 32  Total Costs                          float64
 33  Zip Code - 3 digits                  object
 34  Birth Weight_clean                   float64
dtypes: float64(5), int64(7), object(23)
memory usage: 643.6+ MB

In [32]:
#Rename Birth Weight_clean column to "Birth Weight" and drop the original column
df_clean_2 = df_clean_1.drop(['Birth Weight'], axis=1).rename(columns={"Birth Weight_clean": "Birth Weight"})
df_clean_2.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 2343329 entries, 0 to 2343568
Data columns (total 34 columns):
 #   Column                               Dtype
---  ------                               -----
 0   Hospital Service Area                object
 1   Hospital County                      object
 2   Operating Certificate Number         float64
 3   Permanent Facility Id                float64
 4   Facility Name                        object
 5   Age Group                            object
 6   Gender                               object
 7   Race                                 object
 8   Ethnicity                            object
 9   Length of Stay                       int64
 10  Type of Admission                    object
 11  Patient Disposition                  object
 12  Discharge Year                       int64
 13  CCS Diagnosis Code                   int64
 14  CCS Diagnosis Description            object
 15  CCS Procedure Code                   int64
 16  CCS Procedure Description            object
 17  APR DRG Code                         int64
 18  APR DRG Description                  object
 19  APR MDC Code                         int64
 20  APR MDC Description                  object
 21  APR Severity of Illness Code         int64
 22  APR Severity of Illness Description  object
 23  APR Risk of Mortality                object
 24  APR Medical Surgical Description     object
 25  Payment Typology 1                   object
 26  Payment Typology 2                   object
 27  Payment Typology 3                   object
 28  Abortion Edit Indicator              object
 29  Emergency Department Indicator       object
 30  Total Charges                        float64
 31  Total Costs                          float64
 32  Zip Code - 3 digits                  object
 33  Birth Weight                         float64
dtypes: float64(5), int64(7), object(22)
memory usage: 625.7+ MB

Investigate potential categorical variables

In [27]:
df_clean['APR Risk of Mortality'].value_counts()

Minor       1338452
Moderate     508068
Major        378128
Extreme      118681
Name: APR Risk of Mortality, dtype: int64

In [28]:
df_clean['Payment Typology 1'].value_counts()

Medicare                     906899
Medicaid                     703996
Private Health Insurance     344913
Blue Cross/Blue Shield       262808
Self-Pay                      44657
Managed Care, Unspecified     32315
Miscellaneous/Other           28515
Federal/State/Local/VA        14298
Department of Corrections      2622
Unknown                        2306
Name: Payment Typology 1, dtype: int64

Create new columns to transform categorical variables

In [33]:
age_dict = {'0 to 17': 1, '18 to 29': 2, '30 to 49': 3, '50 to 69': 4, '70 or Older': 5}

mortality_dict = {'Minor': 1, 'Moderate': 2, 'Major': 3, 'Extreme': 4}

payment_typo_dict = {'Medicare': 1, 'Medicaid': 2, 'Private Health Insurance': 3, 
                     'Blue Cross/Blue Shield': 4, 'Self-Pay': 5, 'Managed Care, Unspecified': 6, 
                     'Miscellaneous/Other': 7, 'Federal/State/Local/VA': 8, 
                     'Department of Corrections': 9, 'Unknown': 9999}

apr_medical_surgical_code = {'Medical': 1, 'Surgical': 2}

df_clean_2['age_group_code'] = df_clean_2['Age Group'].apply(lambda x: age_dict[x])
df_clean_2['apr_risk_mortality_code'] = df_clean_2['APR Risk of Mortality'].apply(lambda x: mortality_dict[x])
df_clean_2['payment_typology_1_code'] = df_clean_2['Payment Typology 1'].apply(lambda x: payment_typo_dict[x])
df_clean_2['apr_medical_surgical_code'] = df_clean_2['APR Medical Surgical Description'].\
                    apply(lambda x: apr_medical_surgical_code[x])


df_clean_2.head()

,Hospital Service Area,Hospital County,Operating Certificate Number,Permanent Facility Id,Facility Name,Age Group,Gender,Race,Ethnicity,Length of Stay,...,Abortion Edit Indicator,Emergency Department Indicator,Total Charges,Total Costs,Zip Code - 3 digits,Birth Weight,age_group_code,apr_risk_mortality_code,payment_typology_1_code,apr_medical_surgical_code
0,Hudson Valley,Westchester,5903001.0,1061.0,Montefiore Mount Vernon Hospital,30 to 49,M,White,Not Span/Hispanic,21,...,N,N,114168.00,40464.04,105,NaN,3,1,1,1
1,Hudson Valley,Westchester,5903001.0,1061.0,Montefiore Mount Vernon Hospital,50 to 69,M,White,Spanish/Hispanic,8,...,N,N,58517.00,26046.50,105,NaN,4,2,2,1
2,Hudson Valley,Westchester,5903001.0,1061.0,Montefiore Mount Vernon Hospital,30 to 49,F,White,Unknown,6,...,N,N,39647.04,17397.59,105,NaN,3,2,9,1
3,Hudson Valley,Westchester,5903001.0,1061.0,Montefiore Mount Vernon Hospital,50 to 69,F,White,Not Span/Hispanic,4,...,N,N,36031.09,16118.84,105,NaN,4,2,2,1
4,Hudson Valley,Westchester,5903001.0,1061.0,Montefiore Mount Vernon Hospital,18 to 29,F,White,Spanish/Hispanic,4,...,N,N,30534.00,11921.05,105,NaN,2,1,9,1

In [34]:
df_clean_2.isna().sum()

Hospital Service Area                     5150
Hospital County                           5150
Operating Certificate Number              5150
Permanent Facility Id                     5150
Facility Name                                0
Age Group                                    0
Gender                                       0
Race                                         0
Ethnicity                                    0
Length of Stay                               0
Type of Admission                            0
Patient Disposition                          0
Discharge Year                               0
CCS Diagnosis Code                           0
CCS Diagnosis Description                    0
CCS Procedure Code                           0
CCS Procedure Description                    0
APR DRG Code                                 0
APR DRG Description                          0
APR MDC Code                                 0
APR MDC Description                          0
APR Severity of Illness Code                 0
APR Severity of Illness Description          0
APR Risk of Mortality                        0
APR Medical Surgical Description             0
Payment Typology 1                           0
Payment Typology 2                      878621
Payment Typology 3                     1737034
Abortion Edit Indicator                      0
Emergency Department Indicator               0
Total Charges                                0
Total Costs                                  0
Zip Code - 3 digits                       5150
Birth Weight                           2116114
age_group_code                               0
apr_risk_mortality_code                      0
payment_typology_1_code                      0
apr_medical_surgical_code                    0
dtype: int64

Transform from numeric to string

In [35]:
df_clean_2[["Operating Certificate Number", "Permanent Facility Id"]] = df_clean_2[["Operating Certificate Number", 
                                                                                    "Permanent Facility Id"]].astype(str) 
df_clean_2.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 2343329 entries, 0 to 2343568
Data columns (total 38 columns):
 #   Column                               Dtype
---  ------                               -----
 0   Hospital Service Area                object
 1   Hospital County                      object
 2   Operating Certificate Number         object
 3   Permanent Facility Id                object
 4   Facility Name                        object
 5   Age Group                            object
 6   Gender                               object
 7   Race                                 object
 8   Ethnicity                            object
 9   Length of Stay                       int64
 10  Type of Admission                    object
 11  Patient Disposition                  object
 12  Discharge Year                       int64
 13  CCS Diagnosis Code                   int64
 14  CCS Diagnosis Description            object
 15  CCS Procedure Code                   int64
 16  CCS Procedure Description            object
 17  APR DRG Code                         int64
 18  APR DRG Description                  object
 19  APR MDC Code                         int64
 20  APR MDC Description                  object
 21  APR Severity of Illness Code         int64
 22  APR Severity of Illness Description  object
 23  APR Risk of Mortality                object
 24  APR Medical Surgical Description     object
 25  Payment Typology 1                   object
 26  Payment Typology 2                   object
 27  Payment Typology 3                   object
 28  Abortion Edit Indicator              object
 29  Emergency Department Indicator       object
 30  Total Charges                        float64
 31  Total Costs                          float64
 32  Zip Code - 3 digits                  object
 33  Birth Weight                         float64
 34  age_group_code                       int64
 35  apr_risk_mortality_code              int64
 36  payment_typology_1_code              int64
 37  apr_medical_surgical_code            int64
dtypes: float64(3), int64(11), object(24)
memory usage: 697.2+ MB

### Prepare the data for modeling purpose
- Remove rows with NAs 
- Replace OOS character in the zip code (out of state) with numeric variable 9999
- Remove all unnecessary columns
- Transform all should-have-been-categorical variables to category

In [36]:
#Remove rows with NAs 
df_modeling = df_clean_2.dropna(subset=['Hospital Service Area'])

In [37]:
#Replace OOS character in the zip code (out of state) with numeric variable 9999
df_modeling['Zip Code - 3 digits_clean'] = df_modeling['Zip Code - 3 digits'].apply(lambda x: str(x).replace('OOS','9999'))  
df_modeling['Zip Code - 3 digits_clean'] = pd.to_numeric(df_modeling['Zip Code - 3 digits_clean'])

In [38]:
#Transform all should-have-been-categorical variables to category
df_modeling['CCS Diagnosis Code'] = df_modeling['CCS Diagnosis Code'].astype('category')
df_modeling['CCS Procedure Code'] = df_modeling['CCS Procedure Code'].astype('category')
df_modeling['APR DRG Code'] = df_modeling['APR DRG Code'].astype('category')
df_modeling['APR MDC Code'] = df_modeling['APR MDC Code'].astype('category')
df_modeling['APR Severity of Illness Code'] = df_modeling['APR Severity of Illness Code'].astype('category')
df_modeling['age_group_code'] = df_modeling['age_group_code'].astype('category')
df_modeling['apr_risk_mortality_code'] = df_modeling['apr_risk_mortality_code'].astype('category')
df_modeling['payment_typology_1_code'] = df_modeling['payment_typology_1_code'].astype('category')
df_modeling['apr_medical_surgical_code'] = df_modeling['apr_medical_surgical_code'].astype('category')

In [39]:
df_modeling.info()
df_modeling.isna().sum()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 2338179 entries, 0 to 2343568
Data columns (total 39 columns):
 #   Column                               Dtype
---  ------                               -----
 0   Hospital Service Area                object
 1   Hospital County                      object
 2   Operating Certificate Number         object
 3   Permanent Facility Id                object
 4   Facility Name                        object
 5   Age Group                            object
 6   Gender                               object
 7   Race                                 object
 8   Ethnicity                            object
 9   Length of Stay                       int64
 10  Type of Admission                    object
 11  Patient Disposition                  object
 12  Discharge Year                       int64
 13  CCS Diagnosis Code                   category
 14  CCS Diagnosis Description            object
 15  CCS Procedure Code                   category
 16  CCS Procedure Description            object
 17  APR DRG Code                         category
 18  APR DRG Description                  object
 19  APR MDC Code                         category
 20  APR MDC Description                  object
 21  APR Severity of Illness Code         category
 22  APR Severity of Illness Description  object
 23  APR Risk of Mortality                object
 24  APR Medical Surgical Description     object
 25  Payment Typology 1                   object
 26  Payment Typology 2                   object
 27  Payment Typology 3                   object
 28  Abortion Edit Indicator              object
 29  Emergency Department Indicator       object
 30  Total Charges                        float64
 31  Total Costs                          float64
 32  Zip Code - 3 digits                  object
 33  Birth Weight                         float64
 34  age_group_code                       category
 35  apr_risk_mortality_code              category
 36  payment_typology_1_code              category
 37  apr_medical_surgical_code            category
 38  Zip Code - 3 digits_clean            int64
dtypes: category(9), float64(3), int64(3), object(24)
memory usage: 579.8+ MB

Hospital Service Area                        0
Hospital County                              0
Operating Certificate Number                 0
Permanent Facility Id                        0
Facility Name                                0
Age Group                                    0
Gender                                       0
Race                                         0
Ethnicity                                    0
Length of Stay                               0
Type of Admission                            0
Patient Disposition                          0
Discharge Year                               0
CCS Diagnosis Code                           0
CCS Diagnosis Description                    0
CCS Procedure Code                           0
CCS Procedure Description                    0
APR DRG Code                                 0
APR DRG Description                          0
APR MDC Code                                 0
APR MDC Description                          0
APR Severity of Illness Code                 0
APR Severity of Illness Description          0
APR Risk of Mortality                        0
APR Medical Surgical Description             0
Payment Typology 1                           0
Payment Typology 2                      875990
Payment Typology 3                     1732761
Abortion Edit Indicator                      0
Emergency Department Indicator               0
Total Charges                                0
Total Costs                                  0
Zip Code - 3 digits                          0
Birth Weight                           2111193
age_group_code                               0
apr_risk_mortality_code                      0
payment_typology_1_code                      0
apr_medical_surgical_code                    0
Zip Code - 3 digits_clean                    0
dtype: int64

In [40]:
df_modeling.to_csv('df_modeling.csv')
df_modeling.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 2338179 entries, 0 to 2343568
Data columns (total 39 columns):
 #   Column                               Dtype
---  ------                               -----
 0   Hospital Service Area                object
 1   Hospital County                      object
 2   Operating Certificate Number         object
 3   Permanent Facility Id                object
 4   Facility Name                        object
 5   Age Group                            object
 6   Gender                               object
 7   Race                                 object
 8   Ethnicity                            object
 9   Length of Stay                       int64
 10  Type of Admission                    object
 11  Patient Disposition                  object
 12  Discharge Year                       int64
 13  CCS Diagnosis Code                   category
 14  CCS Diagnosis Description            object
 15  CCS Procedure Code                   category
 16  CCS Procedure Description            object
 17  APR DRG Code                         category
 18  APR DRG Description                  object
 19  APR MDC Code                         category
 20  APR MDC Description                  object
 21  APR Severity of Illness Code         category
 22  APR Severity of Illness Description  object
 23  APR Risk of Mortality                object
 24  APR Medical Surgical Description     object
 25  Payment Typology 1                   object
 26  Payment Typology 2                   object
 27  Payment Typology 3                   object
 28  Abortion Edit Indicator              object
 29  Emergency Department Indicator       object
 30  Total Charges                        float64
 31  Total Costs                          float64
 32  Zip Code - 3 digits                  object
 33  Birth Weight                         float64
 34  age_group_code                       category
 35  apr_risk_mortality_code              category
 36  payment_typology_1_code              category
 37  apr_medical_surgical_code            category
 38  Zip Code - 3 digits_clean            int64
dtypes: category(9), float64(3), int64(3), object(24)
memory usage: 579.8+ MB

In [43]:
#Check duplicate rows
#df_modeling[df_modeling.duplicated(keep = False)].head(10)

#Remove columns that have the same meaning
#Investigate these columns

print(len(df_modeling['APR Severity of Illness Code'].unique()))
print(len(df_modeling['APR Severity of Illness Description'].unique()))

df_modeling['APR Medical Surgical Description'].unique()

#Remove duplicate columns
df_modeling_clean = df_modeling.drop(['CCS Diagnosis Description', 'CCS Procedure Description',
                                     'APR DRG Description', 'APR MDC Description',
                                     'APR Severity of Illness Description',
                                     'APR Risk of Mortality', 'Payment Typology 1', 
                                      'APR Medical Surgical Description'], axis = 1)
df_modeling_clean.info()

4
4
<class 'pandas.core.frame.DataFrame'>
Int64Index: 2338179 entries, 0 to 2343568
Data columns (total 31 columns):
 #   Column                          Dtype
---  ------                          -----
 0   Hospital Service Area           object
 1   Hospital County                 object
 2   Operating Certificate Number    object
 3   Permanent Facility Id           object
 4   Facility Name                   object
 5   Age Group                       object
 6   Gender                          object
 7   Race                            object
 8   Ethnicity                       object
 9   Length of Stay                  int64
 10  Type of Admission               object
 11  Patient Disposition             object
 12  Discharge Year                  int64
 13  CCS Diagnosis Code              category
 14  CCS Procedure Code              category
 15  APR DRG Code                    category
 16  APR MDC Code                    category
 17  APR Severity of Illness Code    category
 18  Payment Typology 2              object
 19  Payment Typology 3              object
 20  Abortion Edit Indicator         object
 21  Emergency Department Indicator  object
 22  Total Charges                   float64
 23  Total Costs                     float64
 24  Zip Code - 3 digits             object
 25  Birth Weight                    float64
 26  age_group_code                  category
 27  apr_risk_mortality_code         category
 28  payment_typology_1_code         category
 29  apr_medical_surgical_code       category
 30  Zip Code - 3 digits_clean       int64
dtypes: category(9), float64(3), int64(3), object(16)
memory usage: 437.1+ MB
<class 'pandas.core.frame.DataFrame'>
Int64Index: 2343329 entries, 0 to 2343568
Data columns (total 38 columns):
 #   Column                               Dtype
---  ------                               -----
 0   Hospital Service Area                object
 1   Hospital County                      object
 2   Operating Certificate Number         object
 3   Permanent Facility Id                object
 4   Facility Name                        object
 5   Age Group                            object
 6   Gender                               object
 7   Race                                 object
 8   Ethnicity                            object
 9   Length of Stay                       int64
 10  Type of Admission                    object
 11  Patient Disposition                  object
 12  Discharge Year                       int64
 13  CCS Diagnosis Code                   int64
 14  CCS Diagnosis Description            object
 15  CCS Procedure Code                   int64
 16  CCS Procedure Description            object
 17  APR DRG Code                         int64
 18  APR DRG Description                  object
 19  APR MDC Code                         int64
 20  APR MDC Description                  object
 21  APR Severity of Illness Code         int64
 22  APR Severity of Illness Description  object
 23  APR Risk of Mortality                object
 24  APR Medical Surgical Description     object
 25  Payment Typology 1                   object
 26  Payment Typology 2                   object
 27  Payment Typology 3                   object
 28  Abortion Edit Indicator              object
 29  Emergency Department Indicator       object
 30  Total Charges                        float64
 31  Total Costs                          float64
 32  Zip Code - 3 digits                  object
 33  Birth Weight                         float64
 34  age_group_code                       int64
 35  apr_risk_mortality_code              int64
 36  payment_typology_1_code              int64
 37  apr_medical_surgical_code            int64
dtypes: float64(3), int64(11), object(24)
memory usage: 697.2+ MB

In [ ]:
#Export modeling data
df_modeling_clean.to_csv('df_modeling_1.csv')

In [ ]:
#Export general data
df_clean_2.info()
df_clean_2.to_csv('df_general.csv')

%history -g